database:
  type: mysql
  host: localhost
  port: 3306

tools:
  serp-api:
    token: ${SERP_API_TOKEN}
  proxy-crawl:
    token: ${PROXY_CRAWL_TOKEN}

vector-dbs:
  - type: qdrant
    api-token: "secret-api-key"
    endpoint: http://localhost:6333 # if in doubt, check scripts/start-qdrant.sh

compute:
  - endpoint: http://localhost:8001/v1/completions
    type: http-openai
    max-batch-size: 128 # in case of Mistral-7B and A6000 GPU, 48G
