version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ai_srv
    volumes:
      - ./mydsl-db:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./qdrant-db:/qdrant/data
    ports:
      - '127.0.0.1:6333:6333'